# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.data_account_response import DataAccountResponse  # noqa: F401,E501
from swagger_server import util


class AccountResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: DataAccountResponse=None):  # noqa: E501
        """AccountResponse - a model defined in Swagger

        :param data: The data of this AccountResponse.  # noqa: E501
        :type data: DataAccountResponse
        """
        self.swagger_types = {
            'data': DataAccountResponse
        }

        self.attribute_map = {
            'data': 'Data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'AccountResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AccountResponse of this AccountResponse.  # noqa: E501
        :rtype: AccountResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> DataAccountResponse:
        """Gets the data of this AccountResponse.


        :return: The data of this AccountResponse.
        :rtype: DataAccountResponse
        """
        return self._data

    @data.setter
    def data(self, data: DataAccountResponse):
        """Sets the data of this AccountResponse.


        :param data: The data of this AccountResponse.
        :type data: DataAccountResponse
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data
