# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.account_product_response_data import AccountProductResponseData  # noqa: F401,E501
from swagger_server import util


class AccountProductResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: AccountProductResponseData=None):  # noqa: E501
        """AccountProductResponse - a model defined in Swagger

        :param data: The data of this AccountProductResponse.  # noqa: E501
        :type data: AccountProductResponseData
        """
        self.swagger_types = {
            'data': AccountProductResponseData
        }

        self.attribute_map = {
            'data': 'Data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'AccountProductResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AccountProductResponse of this AccountProductResponse.  # noqa: E501
        :rtype: AccountProductResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> AccountProductResponseData:
        """Gets the data of this AccountProductResponse.


        :return: The data of this AccountProductResponse.
        :rtype: AccountProductResponseData
        """
        return self._data

    @data.setter
    def data(self, data: AccountProductResponseData):
        """Sets the data of this AccountProductResponse.


        :param data: The data of this AccountProductResponse.
        :type data: AccountProductResponseData
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data
