# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AccountIdentificationCode(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    BBAN = "RU.CBR.BBAN"
    EPID = "RU.CBR.EPID"
    ORID = "RU.CBR.ORID"
    PAN = "RU.CBR.PAN"
    MTEL = "RU.CBR.MTEL"
    def __init__(self):  # noqa: E501
        """AccountIdentificationCode - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'AccountIdentificationCode':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AccountIdentificationCode of this AccountIdentificationCode.  # noqa: E501
        :rtype: AccountIdentificationCode
        """
        return util.deserialize_model(dikt, cls)
