# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.accounts_product_list_response_data import AccountsProductListResponseData  # noqa: F401,E501
from swagger_server import util


class AccountsProductListResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: AccountsProductListResponseData=None):  # noqa: E501
        """AccountsProductListResponse - a model defined in Swagger

        :param data: The data of this AccountsProductListResponse.  # noqa: E501
        :type data: AccountsProductListResponseData
        """
        self.swagger_types = {
            'data': AccountsProductListResponseData
        }

        self.attribute_map = {
            'data': 'Data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'AccountsProductListResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AccountsProductListResponse of this AccountsProductListResponse.  # noqa: E501
        :rtype: AccountsProductListResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> AccountsProductListResponseData:
        """Gets the data of this AccountsProductListResponse.


        :return: The data of this AccountsProductListResponse.
        :rtype: AccountsProductListResponseData
        """
        return self._data

    @data.setter
    def data(self, data: AccountsProductListResponseData):
        """Sets the data of this AccountsProductListResponse.


        :param data: The data of this AccountsProductListResponse.
        :type data: AccountsProductListResponseData
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data
