# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.data_balance_response import DataBalanceResponse  # noqa: F401,E501
from swagger_server import util


class BalanceResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: DataBalanceResponse=None):  # noqa: E501
        """BalanceResponse - a model defined in Swagger

        :param data: The data of this BalanceResponse.  # noqa: E501
        :type data: DataBalanceResponse
        """
        self.swagger_types = {
            'data': DataBalanceResponse
        }

        self.attribute_map = {
            'data': 'Data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'BalanceResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BalanceResponse of this BalanceResponse.  # noqa: E501
        :rtype: BalanceResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> DataBalanceResponse:
        """Gets the data of this BalanceResponse.


        :return: The data of this BalanceResponse.
        :rtype: DataBalanceResponse
        """
        return self._data

    @data.setter
    def data(self, data: DataBalanceResponse):
        """Sets the data of this BalanceResponse.


        :param data: The data of this BalanceResponse.
        :type data: DataBalanceResponse
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data
