# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.financial_institution_identification_code import FinancialInstitutionIdentificationCode  # noqa: F401,E501
from swagger_server import util


class BranchAndFinancialInstitutionIdentification(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, scheme_name: FinancialInstitutionIdentificationCode=None, identification: str=None):  # noqa: E501
        """BranchAndFinancialInstitutionIdentification - a model defined in Swagger

        :param scheme_name: The scheme_name of this BranchAndFinancialInstitutionIdentification.  # noqa: E501
        :type scheme_name: FinancialInstitutionIdentificationCode
        :param identification: The identification of this BranchAndFinancialInstitutionIdentification.  # noqa: E501
        :type identification: str
        """
        self.swagger_types = {
            'scheme_name': FinancialInstitutionIdentificationCode,
            'identification': str
        }

        self.attribute_map = {
            'scheme_name': 'schemeName',
            'identification': 'identification'
        }
        self._scheme_name = scheme_name
        self._identification = identification

    @classmethod
    def from_dict(cls, dikt) -> 'BranchAndFinancialInstitutionIdentification':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BranchAndFinancialInstitutionIdentification of this BranchAndFinancialInstitutionIdentification.  # noqa: E501
        :rtype: BranchAndFinancialInstitutionIdentification
        """
        return util.deserialize_model(dikt, cls)

    @property
    def scheme_name(self) -> FinancialInstitutionIdentificationCode:
        """Gets the scheme_name of this BranchAndFinancialInstitutionIdentification.


        :return: The scheme_name of this BranchAndFinancialInstitutionIdentification.
        :rtype: FinancialInstitutionIdentificationCode
        """
        return self._scheme_name

    @scheme_name.setter
    def scheme_name(self, scheme_name: FinancialInstitutionIdentificationCode):
        """Sets the scheme_name of this BranchAndFinancialInstitutionIdentification.


        :param scheme_name: The scheme_name of this BranchAndFinancialInstitutionIdentification.
        :type scheme_name: FinancialInstitutionIdentificationCode
        """
        if scheme_name is None:
            raise ValueError("Invalid value for `scheme_name`, must not be `None`")  # noqa: E501

        self._scheme_name = scheme_name

    @property
    def identification(self) -> str:
        """Gets the identification of this BranchAndFinancialInstitutionIdentification.

        Банковский идентификационный код (БИК) или другой идентификатор финансового учреждения  # noqa: E501

        :return: The identification of this BranchAndFinancialInstitutionIdentification.
        :rtype: str
        """
        return self._identification

    @identification.setter
    def identification(self, identification: str):
        """Sets the identification of this BranchAndFinancialInstitutionIdentification.

        Банковский идентификационный код (БИК) или другой идентификатор финансового учреждения  # noqa: E501

        :param identification: The identification of this BranchAndFinancialInstitutionIdentification.
        :type identification: str
        """
        if identification is None:
            raise ValueError("Invalid value for `identification`, must not be `None`")  # noqa: E501

        self._identification = identification
