# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.csc_management1_code import CSCManagement1Code  # noqa: F401,E501
import re  # noqa: F401,E501
from swagger_server import util


class CardSecurityInformation1(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, csc_management: CSCManagement1Code=None, csc_value: str=None):  # noqa: E501
        """CardSecurityInformation1 - a model defined in Swagger

        :param csc_management: The csc_management of this CardSecurityInformation1.  # noqa: E501
        :type csc_management: CSCManagement1Code
        :param csc_value: The csc_value of this CardSecurityInformation1.  # noqa: E501
        :type csc_value: str
        """
        self.swagger_types = {
            'csc_management': CSCManagement1Code,
            'csc_value': str
        }

        self.attribute_map = {
            'csc_management': 'CSCManagement',
            'csc_value': 'CSCValue'
        }
        self._csc_management = csc_management
        self._csc_value = csc_value

    @classmethod
    def from_dict(cls, dikt) -> 'CardSecurityInformation1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CardSecurityInformation1 of this CardSecurityInformation1.  # noqa: E501
        :rtype: CardSecurityInformation1
        """
        return util.deserialize_model(dikt, cls)

    @property
    def csc_management(self) -> CSCManagement1Code:
        """Gets the csc_management of this CardSecurityInformation1.


        :return: The csc_management of this CardSecurityInformation1.
        :rtype: CSCManagement1Code
        """
        return self._csc_management

    @csc_management.setter
    def csc_management(self, csc_management: CSCManagement1Code):
        """Sets the csc_management of this CardSecurityInformation1.


        :param csc_management: The csc_management of this CardSecurityInformation1.
        :type csc_management: CSCManagement1Code
        """
        if csc_management is None:
            raise ValueError("Invalid value for `csc_management`, must not be `None`")  # noqa: E501

        self._csc_management = csc_management

    @property
    def csc_value(self) -> str:
        """Gets the csc_value of this CardSecurityInformation1.

        Код безопасности карты  # noqa: E501

        :return: The csc_value of this CardSecurityInformation1.
        :rtype: str
        """
        return self._csc_value

    @csc_value.setter
    def csc_value(self, csc_value: str):
        """Sets the csc_value of this CardSecurityInformation1.

        Код безопасности карты  # noqa: E501

        :param csc_value: The csc_value of this CardSecurityInformation1.
        :type csc_value: str
        """

        self._csc_value = csc_value
