# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.account import Account  # noqa: F401,E501
from swagger_server import util


class DataAccountResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, account: List[Account]=None):  # noqa: E501
        """DataAccountResponse - a model defined in Swagger

        :param account: The account of this DataAccountResponse.  # noqa: E501
        :type account: List[Account]
        """
        self.swagger_types = {
            'account': List[Account]
        }

        self.attribute_map = {
            'account': 'Account'
        }
        self._account = account

    @classmethod
    def from_dict(cls, dikt) -> 'DataAccountResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataAccountResponse of this DataAccountResponse.  # noqa: E501
        :rtype: DataAccountResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def account(self) -> List[Account]:
        """Gets the account of this DataAccountResponse.


        :return: The account of this DataAccountResponse.
        :rtype: List[Account]
        """
        return self._account

    @account.setter
    def account(self, account: List[Account]):
        """Sets the account of this DataAccountResponse.


        :param account: The account of this DataAccountResponse.
        :type account: List[Account]
        """

        self._account = account
