# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.balance import Balance  # noqa: F401,E501
from swagger_server import util


class DataBalanceResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, balance: List[Balance]=None):  # noqa: E501
        """DataBalanceResponse - a model defined in Swagger

        :param balance: The balance of this DataBalanceResponse.  # noqa: E501
        :type balance: List[Balance]
        """
        self.swagger_types = {
            'balance': List[Balance]
        }

        self.attribute_map = {
            'balance': 'Balance'
        }
        self._balance = balance

    @classmethod
    def from_dict(cls, dikt) -> 'DataBalanceResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataBalanceResponse of this DataBalanceResponse.  # noqa: E501
        :rtype: DataBalanceResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def balance(self) -> List[Balance]:
        """Gets the balance of this DataBalanceResponse.


        :return: The balance of this DataBalanceResponse.
        :rtype: List[Balance]
        """
        return self._balance

    @balance.setter
    def balance(self, balance: List[Balance]):
        """Sets the balance of this DataBalanceResponse.


        :param balance: The balance of this DataBalanceResponse.
        :type balance: List[Balance]
        """

        self._balance = balance
