# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.obru_error_response_error_code import OBRUErrorResponseErrorCode  # noqa: F401,E501
from swagger_server import util


class OBRUError(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, error_code: OBRUErrorResponseErrorCode=None, message: str=None, path: str=None, url: str=None):  # noqa: E501
        """OBRUError - a model defined in Swagger

        :param error_code: The error_code of this OBRUError.  # noqa: E501
        :type error_code: OBRUErrorResponseErrorCode
        :param message: The message of this OBRUError.  # noqa: E501
        :type message: str
        :param path: The path of this OBRUError.  # noqa: E501
        :type path: str
        :param url: The url of this OBRUError.  # noqa: E501
        :type url: str
        """
        self.swagger_types = {
            'error_code': OBRUErrorResponseErrorCode,
            'message': str,
            'path': str,
            'url': str
        }

        self.attribute_map = {
            'error_code': 'errorCode',
            'message': 'message',
            'path': 'path',
            'url': 'url'
        }
        self._error_code = error_code
        self._message = message
        self._path = path
        self._url = url

    @classmethod
    def from_dict(cls, dikt) -> 'OBRUError':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OBRUError of this OBRUError.  # noqa: E501
        :rtype: OBRUError
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error_code(self) -> OBRUErrorResponseErrorCode:
        """Gets the error_code of this OBRUError.


        :return: The error_code of this OBRUError.
        :rtype: OBRUErrorResponseErrorCode
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code: OBRUErrorResponseErrorCode):
        """Sets the error_code of this OBRUError.


        :param error_code: The error_code of this OBRUError.
        :type error_code: OBRUErrorResponseErrorCode
        """
        if error_code is None:
            raise ValueError("Invalid value for `error_code`, must not be `None`")  # noqa: E501

        self._error_code = error_code

    @property
    def message(self) -> str:
        """Gets the message of this OBRUError.

        Описание ошибки. Например, 'Обязательное поле не указано'  # noqa: E501

        :return: The message of this OBRUError.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this OBRUError.

        Описание ошибки. Например, 'Обязательное поле не указано'  # noqa: E501

        :param message: The message of this OBRUError.
        :type message: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message

    @property
    def path(self) -> str:
        """Gets the path of this OBRUError.

        Путь к элементу с ошибкой в JSON объекте. Рекомендуемое, но не обязательное поле  # noqa: E501

        :return: The path of this OBRUError.
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path: str):
        """Sets the path of this OBRUError.

        Путь к элементу с ошибкой в JSON объекте. Рекомендуемое, но не обязательное поле  # noqa: E501

        :param path: The path of this OBRUError.
        :type path: str
        """

        self._path = path

    @property
    def url(self) -> str:
        """Gets the url of this OBRUError.

        URL для помощи в устранении проблемы, Также через URL можно предоставлять дополнительную информацию  # noqa: E501

        :return: The url of this OBRUError.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this OBRUError.

        URL для помощи в устранении проблемы, Также через URL можно предоставлять дополнительную информацию  # noqa: E501

        :param url: The url of this OBRUError.
        :type url: str
        """

        self._url = url
