# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.payment_card4 import PaymentCard4  # noqa: F401,E501
from swagger_server import util


class PaymentCards4(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, payment_cards: List[PaymentCard4]=None):  # noqa: E501
        """PaymentCards4 - a model defined in Swagger

        :param payment_cards: The payment_cards of this PaymentCards4.  # noqa: E501
        :type payment_cards: List[PaymentCard4]
        """
        self.swagger_types = {
            'payment_cards': List[PaymentCard4]
        }

        self.attribute_map = {
            'payment_cards': 'PaymentCards'
        }
        self._payment_cards = payment_cards

    @classmethod
    def from_dict(cls, dikt) -> 'PaymentCards4':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PaymentCards4 of this PaymentCards4.  # noqa: E501
        :rtype: PaymentCards4
        """
        return util.deserialize_model(dikt, cls)

    @property
    def payment_cards(self) -> List[PaymentCard4]:
        """Gets the payment_cards of this PaymentCards4.


        :return: The payment_cards of this PaymentCards4.
        :rtype: List[PaymentCard4]
        """
        return self._payment_cards

    @payment_cards.setter
    def payment_cards(self, payment_cards: List[PaymentCard4]):
        """Sets the payment_cards of this PaymentCards4.


        :param payment_cards: The payment_cards of this PaymentCards4.
        :type payment_cards: List[PaymentCard4]
        """

        self._payment_cards = payment_cards
