# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PeriodUnit(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    HOUR = "Hour"
    DAY = "Day"
    WEEK = "Week"
    MONTH = "Month"
    QUARTER = "Quarter"
    HALFYEAR = "HalfYear"
    YEAR = "Year"
    ACADEMICTERM = "AcademicTerm"
    def __init__(self):  # noqa: E501
        """PeriodUnit - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'PeriodUnit':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PeriodUnit of this PeriodUnit.  # noqa: E501
        :rtype: PeriodUnit
        """
        return util.deserialize_model(dikt, cls)
