# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ProductType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    DEPOSITINDIVIDUAL_ = "depositIndividual | Депозит физического лица"
    DEPOSITLEGALENTITY_ = "depositlegalEntity | Депозит юридического лица"
    CAINDIVIDUAL_ = "CAindividual | Текущий счет физического лица"
    CALEGALENTITY_ = "CALegalEntity | Расчетный счет юридического лица"
    DEBITCARD_ = "debitCard | Дебетовая карта"
    CREDITCARD_ = "creditCard | Кредитная карта"
    LOANCAR_ = "loanCar | Автокредит"
    LOANINDIVIDUAL_ = "loanIndividual | Кредит физическому лицу"
    LOANLEGALENTITY_ = "loanLegalEntity | Кредит юридического лица"
    MORTAGE_ = "mortage | Ипотека"
    INVESTMENT_ = "investment | Инвестиционный продукт"
    OTHER_ = "Other | Другой продукт"
    def __init__(self):  # noqa: E501
        """ProductType - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ProductType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProductType of this ProductType.  # noqa: E501
        :rtype: ProductType
        """
        return util.deserialize_model(dikt, cls)
